frontend:
    build:
      context: ./frontend/korp-erp-web
      dockerfile: Dockerfile
    container_name: korp-frontend
    ports:
      - "4200:80"
    depends_on:
      - faturamento-service
      - estoque-service
    networks:
      - korp-network